#!/bin/bash

date '+%a %d.%m. (%B - Week %W)'
date '+%a %d.%m. (%B - Week %W)'
echo "#FFFFFF"

if [[ $BLOCK_BUTTON == "1" ]]; then
    gsimplecal
elif [[ $BLOCK_BUTTON == "3" ]]; then
    gnome-calendar
fi
